package middlewares

import (
	"context"
	"log"
	"net/http"

	"github.com/maximhq/maxim-go/logging"
)

type MaximOpenAITransport struct {
	Logger *logging.Logger
}

func NewMaximOpenAITransport(logger *logging.Logger) *MaximOpenAITransport {
	return &MaximOpenAITransport{
		Logger: logger,
	}
}

func (t *MaximOpenAITransport) Do(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize OpenAITransport with logging.Logger object. Currently Maxim tracing is disabled as logger is not available.")
	}
	var logger *logging.Logger
	if t.Logger != nil {
		logger = t.Logger
	} else {
		logger = autoGeneratedLogger
	}
	ctx := context.WithValue(req.Context(), "maxim.logger", logger)
	ctx = context.WithValue(ctx, "maxim.provider", logging.ProviderAzure)
	req = req.WithContext(ctx)
	return MaximOpenAIMiddleware(req, func(req *http.Request) (*http.Response, error) {
		return http.DefaultTransport.RoundTrip(req)
	})
}
