package middlewares

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/maximhq/maxim-go/logging"
	"github.com/maximhq/maxim-go/schemas"
)

type MaximBedrockHTTPClient struct {
	Logger *logging.Logger
}

func NewMaximBedrockHTTPClient(logger *logging.Logger) *MaximBedrockHTTPClient {
	return &MaximBedrockHTTPClient{
		Logger: logger,
	}
}

func (t *MaximBedrockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize BedrockHTTPClient with logging.Logger object. Currently Maxim tracing is disabled as logger is not available.")
	}
	logger := t.Logger
	if logger == nil {
		logger = autoGeneratedLogger
	}
	if logger != nil {
		ctx := context.WithValue(req.Context(), ContextKeyLogger, logger)
		req = req.WithContext(ctx)
	}
	return MaximBedrockMiddleware(req, func(r *http.Request) (*http.Response, error) {
		return http.DefaultTransport.RoundTrip(r)
	})
}

// MaximBedrockTransport is an http.RoundTripper for AWS Bedrock Converse API.
// Use with AWS SDK: config.WithHTTPClient(&http.Client{Transport: middlewares.NewMaximBedrockTransport(logger)})
type MaximBedrockTransport struct {
	Logger *logging.Logger
}

func NewMaximBedrockTransport(logger *logging.Logger) *MaximBedrockTransport {
	return &MaximBedrockTransport{Logger: logger}
}

func (t *MaximBedrockTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize BedrockTransport with logging.Logger. Maxim tracing is disabled.")
	}
	logger := t.Logger
	if logger == nil {
		logger = autoGeneratedLogger
	}
	if logger != nil {
		ctx := context.WithValue(req.Context(), ContextKeyLogger, logger)
		req = req.WithContext(ctx)
	}
	return MaximBedrockMiddleware(req, func(r *http.Request) (*http.Response, error) {
		return http.DefaultTransport.RoundTrip(r)
	})
}

// MaximBedrockMiddleware is a reusable middleware for Bedrock Converse API.
func MaximBedrockMiddleware(req *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
	var logger *logging.Logger
	if v, ok := req.Context().Value(ContextKeyLogger).(*logging.Logger); ok && v != nil {
		logger = v
	} else if autoGeneratedLogger != nil {
		logger = autoGeneratedLogger
	} else {
		log.Println("[MaximSDK] Logger is not available in the context. Please attach maxim.logger to trace using middlewares")
	}
	var trace *logging.Trace
	var generation *logging.Generation
	var model string
	if logger != nil {
		contextValues := parseContextValues(req.Context())
		provider := logging.ProviderBedrock
		// Clone the body of the request if it exists
		trace = logger.Trace(&logging.TraceConfig{
			Id:   contextValues.TraceId,
			Name: &contextValues.TraceName,
			Tags: &contextValues.TraceTags,
		})
		if !userProvidedTraceContext(req.Context()) {
			defer trace.End()
		}
		for k, v := range contextValues.TraceMetrics {
			trace.AddMetric(k, v)
		}
		// Print all headers from req
		path := req.URL.Path
		if len(path) > 0 && path[0:7] == "/model/" {
			parts := strings.Split(path, "/")
			if len(parts) > 2 {
				modelParts := strings.Split(parts[2], ":")
				if len(modelParts) > 0 {
					model = modelParts[0]
					// Strip "global." prefix (e.g. cross-region inference profile)
					model = strings.TrimPrefix(model, "global.")
				}
			}
		}
		var body map[string]interface{}
		if req.Body != nil {
			bodyBytes, err := io.ReadAll(req.Body)
			if err != nil {
				return nil, err
			}
			_ = req.Body.Close()
			// Create two readers from the bytes
			req.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Note: We don't need to create a second reader here since we're just passing through
			// If needed, create another reader: bodyClone := io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Print the request body for debugging
			if err := json.Unmarshal(bodyBytes, &body); err != nil {
				// Log or handle the error as needed
				// For now, just continue with the execution
				log.Print("[MaximSDK] Couldn't parse Bedrock request")
			}
		}
		// Ensure required fields are present
		if body == nil {
			log.Print("[MaximSDK] Request body is empty")
			body = make(map[string]interface{})
		}
		var messages []schemas.CompletionRequest
		// Process messages array
		if _, ok := body["messages"].([]interface{}); ok {
			payloadMessages := body["messages"].([]interface{})
			numMessages := len(payloadMessages)
			// Add system messages if they exist
			var systemMessages []interface{}
			if sys, ok := body["system"].([]interface{}); ok {
				systemMessages = sys
				numMessages += len(systemMessages)
			}
			messages = make([]schemas.CompletionRequest, 0, numMessages)
			// Process system messages if they exist
			for _, sysMsg := range systemMessages {
				if sysMsgMap, ok := sysMsg.(map[string]interface{}); ok {
					messages = append(messages, schemas.CompletionRequest{
						Role:    "system",
						Content: sysMsgMap["text"],
					})
				}
			}
			// Process regular messages
			for _, msg := range payloadMessages {
				if msgMap, ok := msg.(map[string]interface{}); ok {
					var content string
					if contentArray, ok := msgMap["content"].([]interface{}); ok {
						var texts []string
						for _, contentItem := range contentArray {
							if contentMap, ok := contentItem.(map[string]interface{}); ok {
								if text, ok := contentMap["text"].(string); ok {
									texts = append(texts, text)
								}
							}
						}
						content = strings.Join(texts, "\n")
					}
					messages = append(messages, schemas.CompletionRequest{
						Role:    msgMap["role"].(string),
						Content: content,
					})
				}
			}
		}
		// Extract model parameters into a separate map
		modelParams := make(map[string]interface{})
		if _, ok := body["inferenceConfig"].(map[string]interface{}); ok {
			modelParams = body["inferenceConfig"].(map[string]interface{})
		}
		// Checking it toolConfig is present, if yes we use that as tool
		if _, ok := body["toolConfig"].([]interface{}); ok {
			modelParams["tools"] = body["toolConfig"].([]interface{})
		}
		if model != "" {
			generation = trace.AddGeneration(&logging.GenerationConfig{
				Id:              uuid.New().String(),
				Name:            &contextValues.GenerationName,
				Provider:        provider,
				Model:           model,
				ModelParameters: modelParams,
				Messages:        messages,
				Tags:            &contextValues.GenerationTags,
			})
			defer generation.End()
			for k, v := range contextValues.GenerationMetrics {
				generation.AddMetric(k, v)
			}
			addAttachmentsFromBedrockMessages(body, generation)
		}
	}
	resp, originalErr := next(req)
	if logger != nil {
		var result map[string]interface{}
		if resp != nil && resp.Body != nil {
			respBytes, err := io.ReadAll(resp.Body)
			_ = resp.Body.Close()
			if err != nil {
				log.Print("[MaximSDK] Error reading response body:", err)
			} else {
				// Create a new reader from the bytes
				resp.Body = io.NopCloser(bytes.NewBuffer(respBytes))
			}
			// Parse response bytes into result
			if err := json.Unmarshal(respBytes, &result); err != nil {
				log.Print("[MaximSDK] Error parsing Bedrock response:", err)
			}
		}
		if generation != nil {
			apiErr := extractBedrockAPIError(resp, result)
			if originalErr != nil {
				generation.SetError(&schemas.GenerationError{
					Message: originalErr.Error(),
				})
			} else if apiErr != nil {
				generation.SetError(apiErr)
				generation.SetResult(result)
			} else {
				br, err := logging.ParseResult(logging.ProviderBedrock, model, result)
				if err != nil {
					log.Println("[MaximSDK] Error parsing Bedrock response:", err)
				} else {
					trace.SetOutput(br.Choices[0].Message.Content)
				}
				generation.SetResult(result)
			}
		}
	}
	return resp, originalErr
}

// extractBedrockAPIError extracts API-level errors from the Bedrock response.
// AWS APIs return {"__type": "ValidationException", "message": "..."} or {"message": "..."}.
func extractBedrockAPIError(resp *http.Response, result map[string]interface{}) *schemas.GenerationError {
	if resp != nil && resp.StatusCode >= 400 {
		if result != nil {
			msg, _ := result["message"].(string)
			if msg == "" {
				msg = resp.Status
			}
			if msg == "" {
				msg = http.StatusText(resp.StatusCode)
			}
			ge := &schemas.GenerationError{Message: msg}
			if errType, ok := result["__type"].(string); ok {
				ge.Type = &errType
			}
			return ge
		}
		return &schemas.GenerationError{
			Message: resp.Status,
		}
	}
	return nil
}

// addAttachmentsFromBedrockMessages extracts image blocks from Bedrock Converse messages
// and adds them as attachments to the generation for display in Maxim.
func addAttachmentsFromBedrockMessages(body map[string]interface{}, generation *logging.Generation) {
	if body == nil || generation == nil {
		return
	}
	messages, ok := body["messages"].([]interface{})
	if !ok {
		return
	}
	for _, m := range messages {
		msgMap, ok := m.(map[string]interface{})
		if !ok {
			continue
		}
		contentArr, ok := msgMap["content"].([]interface{})
		if !ok {
			continue
		}
		for _, block := range contentArr {
			blockMap, ok := block.(map[string]interface{})
			if !ok {
				continue
			}
			imgObj := blockMap["image"]
			if imgObj == nil {
				continue
			}
			imgMap, ok := imgObj.(map[string]interface{})
			if !ok {
				continue
			}
			if att := attachmentFromBedrockImage(imgMap); att != nil {
				generation.AddAttachment(att)
			}
		}
	}
}

func attachmentFromBedrockImage(imgMap map[string]interface{}) interface{} {
	source, ok := imgMap["source"].(map[string]interface{})
	if !ok {
		return nil
	}
	// source.bytes (base64) -> FileDataAttachment
	if bytesVal, ok := source["bytes"].(string); ok && bytesVal != "" {
		data, err := base64.StdEncoding.DecodeString(bytesVal)
		if err != nil {
			log.Printf("[MaximSDK] Failed to decode Bedrock image bytes: %v", err)
			return nil
		}
		format, _ := imgMap["format"].(string)
		if format == "" {
			format = "jpeg"
		}
		mimeType := "image/" + format
		ext := "." + format
		return &logging.FileDataAttachment{
			BaseAttachmentProps: logging.BaseAttachmentProps{
				ID:       uuid.New().String(),
				Name:     "input_image" + ext,
				MimeType: mimeType,
				Tags:     map[string]string{"source": "bedrock_vision_input"},
			},
			Type: logging.AttachmentTypeFileData,
			Data: data,
		}
	}
	// source.s3Location.uri -> UrlAttachment
	if s3Loc, ok := source["s3Location"].(map[string]interface{}); ok {
		uriVal, ok := s3Loc["uri"].(string)
		if !ok || uriVal == "" {
			return nil
		}
		return &logging.UrlAttachment{
			BaseAttachmentProps: logging.BaseAttachmentProps{
				ID:       uuid.New().String(),
				Name:     "input_image",
				MimeType: "application/octet-stream",
				Tags:     map[string]string{"source": "bedrock_vision_input"},
			},
			Type: logging.AttachmentTypeURL,
			URL:  uriVal,
		}
	}
	return nil
}
