package middlewares

import (
	"bytes"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/maximhq/maxim-go/logging"
)

type MaximBedrockHTTPClient struct {
	Logger *logging.Logger
}

func NewMaximBedrockHTTPClient(logger *logging.Logger) *MaximBedrockHTTPClient {
	return &MaximBedrockHTTPClient{
		Logger: logger,
	}
}

func (t *MaximBedrockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize BedrockHTTPClient with logging.Logger object. Currently Maxim tracing is disabled as logger is not available.")
	}
	var logger *logging.Logger
	if t.Logger != nil {
		logger = t.Logger
	} else {
		logger = autoGeneratedLogger
	}
	var trace *logging.Trace
	var generation *logging.Generation
	if logger != nil {
		contextValues := parseContextValues(req.Context())
		provider := logging.ProviderBedrock
		// Clone the body of the request if it exists
		trace = logger.Trace(&logging.TraceConfig{
			Id:   contextValues.TraceId,
			Name: &contextValues.TraceName,
			Tags: &contextValues.TraceTags,
		})
		// Print all headers from req
		path := req.URL.Path
		var model string
		if len(path) > 0 && path[0:7] == "/model/" {
			parts := strings.Split(path, "/")
			if len(parts) > 2 {
				modelParts := strings.Split(parts[2], ":")
				if len(modelParts) > 0 {
					model = modelParts[0]
				}
			}
		}
		var body map[string]interface{}
		if req.Body != nil {
			bodyBytes, err := io.ReadAll(req.Body)
			if err != nil {
				return nil, err
			}
			// Create two readers from the bytes
			req.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Note: We don't need to create a second reader here since we're just passing through
			// If needed, create another reader: bodyClone := io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Print the request body for debugging
			if err := json.Unmarshal(bodyBytes, &body); err != nil {
				// Log or handle the error as needed
				// For now, just continue with the execution
				log.Print("[MaximSDK] Couldn't parse Bedrock request")
			}
		}
		// Ensure required fields are present
		if body == nil {
			log.Print("[MaximSDK] Request body is empty")
			body = make(map[string]interface{})
		}
		var messages []logging.CompletionRequest
		// Process messages array
		if _, ok := body["messages"].([]interface{}); ok {
			payloadMessages := body["messages"].([]interface{})
			numMessages := len(payloadMessages)
			// Add system messages if they exist
			var systemMessages []interface{}
			if sys, ok := body["system"].([]interface{}); ok {
				systemMessages = sys
				numMessages += len(systemMessages)
			}
			messages = make([]logging.CompletionRequest, 0, numMessages)
			// Process system messages if they exist
			for _, sysMsg := range systemMessages {
				if sysMsgMap, ok := sysMsg.(map[string]interface{}); ok {
					messages = append(messages, logging.CompletionRequest{
						Role:    "system",
						Content: sysMsgMap["text"],
					})
				}
			}
			// Process regular messages
			for _, msg := range payloadMessages {
				if msgMap, ok := msg.(map[string]interface{}); ok {
					var content string
					if contentArray, ok := msgMap["content"].([]interface{}); ok {
						var texts []string
						for _, contentItem := range contentArray {
							if contentMap, ok := contentItem.(map[string]interface{}); ok {
								if text, ok := contentMap["text"].(string); ok {
									texts = append(texts, text)
								}
							}
						}
						content = strings.Join(texts, "\n")
					}
					messages = append(messages, logging.CompletionRequest{
						Role:    msgMap["role"].(string),
						Content: content,
					})
				}
			}
		}
		// Extract model parameters into a separate map
		modelParams := make(map[string]interface{})
		if _, ok := body["inferenceConfig"].(map[string]interface{}); ok {
			modelParams = body["inferenceConfig"].(map[string]interface{})
		}
		// Checking it toolConfig is present, if yes we use that as tool
		if _, ok := body["toolConfig"].([]interface{}); ok {
			modelParams["tools"] = body["toolConfig"].([]interface{})
		}
		if model != "" {
			generation = trace.AddGeneration(&logging.GenerationConfig{
				Id:              uuid.New().String(),
				Name:            &contextValues.GenerationName,
				Provider:        provider,
				Model:           model,
				ModelParameters: modelParams,
				Messages:        messages,
				Tags:            &contextValues.GenerationTags,
			})
			defer generation.End()
		}
	}
	resp, originalErr := http.DefaultTransport.RoundTrip(req)
	if logger != nil {
		var result map[string]interface{}
		if resp != nil && resp.Body != nil {
			respBytes, err := io.ReadAll(resp.Body)
			if err != nil {
				log.Print("[MaximSDK] Error reading response body:", err)
			} else {
				// Create a new reader from the bytes
				resp.Body = io.NopCloser(bytes.NewBuffer(respBytes))
			}
			// Parse response bytes into result
			if err := json.Unmarshal(respBytes, &result); err != nil {
				log.Print("[MaximSDK] Error parsing Bedrock response:", err)
			}
		}
		if generation != nil {
			if originalErr != nil {
				generation.SetError(&logging.GenerationError{
					Message: originalErr.Error(),
				})
			} else {
				generation.SetResult(result)
			}
		}
	}
	return resp, originalErr
}
