package middlewares

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/maximhq/maxim-go/logging"
	"github.com/maximhq/maxim-go/schemas"
)

type MaximGeminiTransport struct {
	Logger *logging.Logger
}

func NewMaximGeminiTransport(logger *logging.Logger) *MaximGeminiTransport {
	return &MaximGeminiTransport{
		Logger: logger,
	}
}

func (t *MaximGeminiTransport) Do(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize GeminiHTTPClient with logging.Logger object. Currently Maxim tracing is disabled as logger is not available.")
	}
	var logger *logging.Logger
	if t.Logger != nil {
		logger = t.Logger
	} else {
		logger = autoGeneratedLogger
	}
	if logger != nil {
		ctx := context.WithValue(req.Context(), ContextKeyLogger, logger)
		ctx = context.WithValue(ctx, ContextKeyProvider, logging.ProviderGemini)
		req = req.WithContext(ctx)
	}
	return MaximGeminiMiddleware(req, func(req *http.Request) (*http.Response, error) {
		return http.DefaultTransport.RoundTrip(req)
	})
}

// MaximGeminiMiddleware is a reusable middleware for Gemini-compatible APIs (e.g. Vertex AI).
// It gets the logger from request context (maxim.logger) or falls back to auto-generated logger.
// Provider can be overridden via context (maxim.provider) for Vertex AI or other Gemini-compatible providers.
func MaximGeminiMiddleware(r *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
	var resp *http.Response
	var logger *logging.Logger
	if r.Context().Value(ContextKeyLogger) != nil {
		logger = r.Context().Value(ContextKeyLogger).(*logging.Logger)
	} else if autoGeneratedLogger != nil {
		logger = autoGeneratedLogger
	} else {
		log.Println("[MaximSDK] Logger is not available in the context. Please attach maxim.logger to logging.Logger to trace using middlewares")
	}
	var trace *logging.Trace
	var generation *logging.Generation
	var model string
	if logger != nil {
		provider := logging.ProviderGemini
		if r.Context().Value(ContextKeyProvider) != nil {
			provider = r.Context().Value(ContextKeyProvider).(string)
		}
		contextValues := parseContextValues(r.Context())
		trace = logger.Trace(&logging.TraceConfig{
			Id:   contextValues.TraceId,
			Name: &contextValues.TraceName,
			Tags: &contextValues.TraceTags,
		})
		if !userProvidedTraceContext(r.Context()) {
			defer trace.End()
		}
		for k, v := range contextValues.TraceMetrics {
			trace.AddMetric(k, v)
		}
		model = extractGeminiModel(r.URL.Path)
		var body map[string]interface{}
		if r.Body != nil {
			bodyBytes, err := io.ReadAll(r.Body)
			if err != nil {
				return nil, err
			}
			_ = r.Body.Close()
			r.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
			if err := json.Unmarshal(bodyBytes, &body); err != nil {
				log.Print("[MaximSDK] Couldn't parse Gemini request")
			}
		}
		if body == nil {
			body = make(map[string]interface{})
		}
		var messages []schemas.CompletionRequest
		// Gemini uses "contents" array: [{ "role": "user", "parts": [{ "text": "..." }] }]
		if contents, ok := body["contents"].([]interface{}); ok {
			for _, c := range contents {
				if contentMap, ok := c.(map[string]interface{}); ok {
					role := "user"
					if r, ok := contentMap["role"].(string); ok {
						role = r
					}
					var textParts []string
					if parts, ok := contentMap["parts"].([]interface{}); ok {
						for _, p := range parts {
							if partMap, ok := p.(map[string]interface{}); ok {
								if text, ok := partMap["text"].(string); ok {
									textParts = append(textParts, text)
								}
							}
						}
					}
					content := strings.Join(textParts, "\n")
					messages = append(messages, schemas.CompletionRequest{
						Role:    role,
						Content: content,
					})
				}
			}
		}
		// Add system instruction as system message if present
		if sysInst, ok := body["systemInstruction"].(map[string]interface{}); ok {
			var sysTextParts []string
			if parts, ok := sysInst["parts"].([]interface{}); ok {
				for _, p := range parts {
					if partMap, ok := p.(map[string]interface{}); ok {
						if text, ok := partMap["text"].(string); ok {
							sysTextParts = append(sysTextParts, text)
						}
					}
				}
			}
			sysMsg := schemas.CompletionRequest{
				Role:    "system",
				Content: strings.Join(sysTextParts, "\n"),
			}
			messages = append([]schemas.CompletionRequest{sysMsg}, messages...)
		}
		modelParams := make(map[string]interface{})
		if genConfig, ok := body["generationConfig"].(map[string]interface{}); ok {
			modelParams = genConfig
		}
		if tools, ok := body["tools"]; ok {
			modelParams["tools"] = tools
		}
		if model != "" {
			generation = trace.AddGeneration(&logging.GenerationConfig{
				Id:              uuid.New().String(),
				Name:            &contextValues.GenerationName,
				Provider:        provider,
				Model:           model,
				ModelParameters: modelParams,
				Messages:        messages,
				Tags:            &contextValues.GenerationTags,
			})
			defer generation.End()
			for k, v := range contextValues.GenerationMetrics {
				generation.AddMetric(k, v)
			}
			addAttachmentsFromRequestParts(body, generation)
		}
	}
	resp, originalErr := next(r)
	if logger != nil {
		var result map[string]interface{}
		streamRequest := strings.Contains(r.URL.Path, "streamGenerateContent")
		if resp != nil && resp.Body != nil {
			respBytes, err := io.ReadAll(resp.Body)
			_ = resp.Body.Close()
			if err != nil {
				log.Print("[MaximSDK] Error reading response body:", err)
			}
			// Always restore body so downstream consumers can read (even if partial)
			resp.Body = io.NopCloser(bytes.NewBuffer(respBytes))
			if streamRequest && resp.StatusCode < 400 && len(respBytes) > 0 {
				result = parseGeminiStreamResponse(respBytes, model)
			} else if err := json.Unmarshal(respBytes, &result); err != nil {
				if !streamRequest {
					log.Print("[MaximSDK] Error parsing Gemini response:", err)
				}
			}
		}
		if generation != nil {
			apiErr := extractGeminiAPIError(resp, result)
			if originalErr != nil {
				generation.SetError(&schemas.GenerationError{
					Message: originalErr.Error(),
				})
			} else if apiErr != nil {
				generation.SetError(apiErr)
				generation.SetResult(result)
			} else {
				gr, err := logging.ParseResult(logging.ProviderGemini, model, result)
				if err != nil {
					log.Println("[MaximSDK] Error parsing Gemini response:", err)
				} else if len(gr.Choices) > 0 {
					trace.SetOutput(gr.Choices[0].Message.Content)
				}
				generation.SetResult(result)
			}
		}
	}
	return resp, originalErr
}

// parseGeminiStreamResponse parses an SSE stream response and returns an aggregated result
// in the same shape as a non-streaming Gemini generateContent response.
func parseGeminiStreamResponse(respBytes []byte, model string) map[string]interface{} {
	var content strings.Builder
	var functionCallParts []map[string]interface{}
	var usageMetadata map[string]interface{}
	var finishReason string

	lines := strings.Split(string(respBytes), "\n")
	for _, line := range lines {
		data, ok := strings.CutPrefix(line, "data: ")
		if !ok {
			continue
		}
		if data == "" || data == "[DONE]" {
			continue
		}
		var chunk map[string]interface{}
		if err := json.Unmarshal([]byte(data), &chunk); err != nil {
			continue
		}
		if usageMetadata == nil {
			if u, ok := chunk["usageMetadata"].(map[string]interface{}); ok {
				usageMetadata = u
			}
		}
		candidates, _ := chunk["candidates"].([]interface{})
		if len(candidates) == 0 {
			continue
		}
		cand, _ := candidates[0].(map[string]interface{})
		if fr, ok := cand["finishReason"].(string); ok && fr != "" {
			finishReason = fr
		}
		c, _ := cand["content"].(map[string]interface{})
		parts, _ := c["parts"].([]interface{})
		for _, p := range parts {
			part, ok := p.(map[string]interface{})
			if !ok {
				continue
			}
			if text, ok := part["text"].(string); ok && text != "" {
				content.WriteString(text)
			}
			if fc, ok := part["functionCall"].(map[string]interface{}); ok {
				functionCallParts = append(functionCallParts, map[string]interface{}{
					"functionCall": fc,
				})
			}
		}
	}
	if usageMetadata == nil {
		usageMetadata = map[string]interface{}{
			"promptTokenCount":     0,
			"candidatesTokenCount": 0,
			"totalTokenCount":      0,
		}
	}
	if finishReason == "" {
		finishReason = "STOP"
	}
	resultParts := []map[string]interface{}{}
	if content.Len() > 0 {
		resultParts = append(resultParts, map[string]interface{}{"text": content.String()})
	}
	resultParts = append(resultParts, functionCallParts...)
	if len(resultParts) == 0 {
		resultParts = append(resultParts, map[string]interface{}{"text": ""})
	}
	result := map[string]interface{}{
		"candidates": []map[string]interface{}{
			{
				"content": map[string]interface{}{
					"parts": resultParts,
					"role":  "model",
				},
				"finishReason": finishReason,
				"index":        0,
			},
		},
		"usageMetadata": usageMetadata,
		"modelVersion":  model,
	}
	return result
}

// extractGeminiAPIError extracts API-level errors from the Gemini response.
// Gemini returns errors as HTTP 4xx/5xx with body like {"error": {"code": 404, "message": "...", "status": "NOT_FOUND"}}.
func extractGeminiAPIError(resp *http.Response, result map[string]interface{}) *schemas.GenerationError {
	if result == nil {
		if resp != nil && resp.StatusCode >= 400 {
			msg := resp.Status
			if msg == "" {
				msg = http.StatusText(resp.StatusCode)
			}
			return &schemas.GenerationError{Message: msg}
		}
		return nil
	}
	// Check for {"error": {"message": "...", "code": ..., "status": "..."}}
	if errObj, ok := result["error"]; ok && errObj != nil {
		switch e := errObj.(type) {
		case map[string]interface{}:
			msg, _ := e["message"].(string)
			if msg == "" {
				msg = "unknown API error"
			}
			ge := &schemas.GenerationError{Message: msg}
			if code, ok := e["code"].(float64); ok {
				c := http.StatusText(int(code))
				ge.Code = &c
			}
			if status, ok := e["status"].(string); ok {
				ge.Type = &status
			}
			return ge
		}
	}
	// Check for top-level {"message": "...", "code": ...} (some Google APIs)
	if msg, ok := result["message"].(string); ok && msg != "" && (resp == nil || resp.StatusCode >= 400) {
		ge := &schemas.GenerationError{Message: msg}
		if code, ok := result["code"].(float64); ok {
			c := http.StatusText(int(code))
			ge.Code = &c
		}
		return ge
	}
	// HTTP error status but no parsed error in body
	if resp != nil && resp.StatusCode >= 400 {
		return &schemas.GenerationError{
			Message: resp.Status,
		}
	}
	return nil
}

// addAttachmentsFromRequestParts extracts inline_data and file_data from Gemini request parts
// and adds them as attachments to the generation for display in Maxim.
func addAttachmentsFromRequestParts(body map[string]interface{}, generation *logging.Generation) {
	if body == nil || generation == nil {
		return
	}
	contents, ok := body["contents"].([]interface{})
	if !ok {
		return
	}
	idx := 0
	for _, c := range contents {
		contentMap, ok := c.(map[string]interface{})
		if !ok {
			continue
		}
		parts, ok := contentMap["parts"].([]interface{})
		if !ok {
			continue
		}
		for _, p := range parts {
			partMap, ok := p.(map[string]interface{})
			if !ok {
				continue
			}
			// Handle inline_data (base64) -> FileDataAttachment
			if att := attachmentFromInlineData(partMap); att != nil {
				generation.AddAttachment(att)
				idx++
				continue
			}
			// Handle file_data (file_uri) -> UrlAttachment
			if att := attachmentFromFileData(partMap); att != nil {
				generation.AddAttachment(att)
				idx++
			}
		}
	}
}

func attachmentFromInlineData(partMap map[string]interface{}) *logging.FileDataAttachment {
	inlineObj := partMap["inline_data"]
	if inlineObj == nil {
		inlineObj = partMap["inlineData"]
	}
	if inlineObj == nil {
		return nil
	}
	inlineMap, ok := inlineObj.(map[string]interface{})
	if !ok {
		return nil
	}
	dataVal := inlineMap["data"]
	if dataVal == nil {
		dataVal = inlineMap["Data"]
	}
	dataStr, ok := dataVal.(string)
	if !ok || dataStr == "" {
		return nil
	}
	data, err := base64.StdEncoding.DecodeString(dataStr)
	if err != nil {
		log.Printf("[MaximSDK] Failed to decode inline_data base64: %v", err)
		return nil
	}
	mimeType, _ := inlineMap["mime_type"].(string)
	if mimeType == "" {
		mimeType, _ = inlineMap["mimeType"].(string)
	}
	if mimeType == "" {
		mimeType = "application/octet-stream"
	}
	ext := ".bin"
	if strings.HasPrefix(mimeType, "image/") {
		ext = "." + strings.TrimPrefix(mimeType, "image/")
	}
	return &logging.FileDataAttachment{
		BaseAttachmentProps: logging.BaseAttachmentProps{
			ID:       uuid.New().String(),
			Name:     "input_image" + ext,
			MimeType: mimeType,
			Tags:     map[string]string{"source": "gemini_vision_input"},
		},
		Type: logging.AttachmentTypeFileData,
		Data: data,
	}
}

func attachmentFromFileData(partMap map[string]interface{}) *logging.UrlAttachment {
	fileObj := partMap["file_data"]
	if fileObj == nil {
		fileObj = partMap["fileData"]
	}
	if fileObj == nil {
		return nil
	}
	fileMap, ok := fileObj.(map[string]interface{})
	if !ok {
		return nil
	}
	uriVal := fileMap["file_uri"]
	if uriVal == nil {
		uriVal = fileMap["fileUri"]
	}
	uriStr, ok := uriVal.(string)
	if !ok || uriStr == "" {
		return nil
	}
	mimeType, _ := fileMap["mime_type"].(string)
	if mimeType == "" {
		mimeType, _ = fileMap["mimeType"].(string)
	}
	ext := ".bin"
	if strings.HasPrefix(mimeType, "image/") {
		ext = "." + strings.TrimPrefix(mimeType, "image/")
	}
	return &logging.UrlAttachment{
		BaseAttachmentProps: logging.BaseAttachmentProps{
			ID:       uuid.New().String(),
			Name:     "input_image" + ext,
			MimeType: mimeType,
			Tags:     map[string]string{"source": "gemini_vision_input"},
		},
		Type: logging.AttachmentTypeURL,
		URL:  uriStr,
	}
}

// extractGeminiModel extracts the model name from the Gemini API URL path.
// Supports: /v1beta/models/{model}:generateContent and Vertex AI paths.
func extractGeminiModel(path string) string {
	if idx := strings.Index(path, "models/"); idx >= 0 {
		modelPart := path[idx+7:] // len("models/") = 7
		if colon := strings.Index(modelPart, ":"); colon >= 0 {
			return modelPart[:colon]
		}
		return modelPart
	}
	return ""
}
