package middlewares

import (
	"os"

	"github.com/maximhq/maxim-go"
	"github.com/maximhq/maxim-go/logging"
)

var autoGeneratedLogger *logging.Logger

func init() {
	apiKey := os.Getenv("MAXIM_API_KEY")
	logRepoId := os.Getenv("LOG_REPO_ID")
	if apiKey != "" && logRepoId != "" {
		autoGeneratedLogger, _ = maxim.Init(&maxim.MaximSDKConfig{}).GetLogger(&logging.LoggerConfig{})
	}
}
