package middlewares

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/maximhq/maxim-go/logging"
	"github.com/maximhq/maxim-go/schemas"
)

// MaximOpenAIAPITransport is an http.RoundTripper for the OpenAI API (api.openai.com)
// and Azure OpenAI. Use with http.Client{Transport: middlewares.NewMaximOpenAIAPITransport(logger)}.
type MaximOpenAIAPITransport struct {
	Logger   *logging.Logger
	provider string
}

// NewMaximOpenAIAPITransport creates a transport for tracing OpenAI API calls to Maxim.
func NewMaximOpenAIAPITransport(logger *logging.Logger) *MaximOpenAIAPITransport {
	return NewMaximOpenAIAPITransportWithProvider(logger, logging.ProviderOpenAI)
}

// NewMaximOpenAIAPITransportWithProvider creates a transport with a specific provider
// (e.g. logging.ProviderOpenAI or logging.ProviderAzure) for tracing to Maxim.
func NewMaximOpenAIAPITransportWithProvider(logger *logging.Logger, provider string) *MaximOpenAIAPITransport {
	if provider == "" {
		provider = logging.ProviderOpenAI
	}
	return &MaximOpenAIAPITransport{Logger: logger, provider: provider}
}

// RoundTrip implements http.RoundTripper for use with http.Client.
func (t *MaximOpenAIAPITransport) RoundTrip(req *http.Request) (*http.Response, error) {
	return t.Do(req)
}

func (t *MaximOpenAIAPITransport) Do(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize OpenAIAPITransport with logging.Logger. Maxim tracing is disabled.")
	}
	logger := t.Logger
	if logger == nil {
		logger = autoGeneratedLogger
	}
	if logger != nil {
		ctx := context.WithValue(req.Context(), ContextKeyLogger, logger)
		provider := t.provider
		if provider == "" {
			provider = logging.ProviderOpenAI
		}
		ctx = context.WithValue(ctx, ContextKeyProvider, provider)
		req = req.WithContext(ctx)
	}
	return MaximOpenAIMiddleware(req, func(r *http.Request) (*http.Response, error) {
		return http.DefaultTransport.RoundTrip(r)
	})
}

func MaximOpenAIMiddleware(r *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
	var resp *http.Response
	var logger *logging.Logger
	var body map[string]interface{}
	// Getting logger
	if v, ok := r.Context().Value(ContextKeyLogger).(*logging.Logger); ok && v != nil {
		logger = v
	} else if autoGeneratedLogger != nil {
		logger = autoGeneratedLogger
	} else {
		log.Println("[MaximSDK] Logger is not available in the context. Please attach maxim.logger to logging.Logger to trace using middlewares")
	}
	var trace *logging.Trace
	var generation *logging.Generation
	if logger != nil {
		provider := logging.ProviderOpenAI
		if v, ok := r.Context().Value(ContextKeyProvider).(string); ok && v != "" {
			provider = v
		}
		contextValues := parseContextValues(r.Context())
		// Clone the body of the request if it exists
		trace = logger.Trace(&logging.TraceConfig{
			Id:   contextValues.TraceId,
			Name: &contextValues.TraceName,
			Tags: &contextValues.TraceTags,
		})
		if !userProvidedTraceContext(r.Context()) {
			defer trace.End()
		}
		for k, v := range contextValues.TraceMetrics {
			trace.AddMetric(k, v)
		}
		body = make(map[string]interface{})
		if r.Body != nil {
			bodyBytes, err := io.ReadAll(r.Body)
			if err != nil {
				return nil, err
			}
			_ = r.Body.Close()
			// Create two readers from the bytes
			r.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Note: We don't need to create a second reader here since we're just passing through
			// If needed, create another reader: bodyClone := io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Print the request body for debugging
			if err := json.Unmarshal(bodyBytes, &body); err != nil {
				// Log or handle the error as needed
				// For now, just continue with the execution
				log.Print("[MaximSDK] Couldn't parse OpenAI request")
			}
			// For streaming requests, add stream_options to request usage in the final chunk
			if streamVal, ok := body["stream"]; ok {
				streamOn := false
				switch v := streamVal.(type) {
				case bool:
					streamOn = v
				case *bool:
					streamOn = v != nil && *v
				}
				if streamOn && body["stream_options"] == nil {
					body["stream_options"] = map[string]interface{}{"include_usage": true}
					if modBytes, err := json.Marshal(body); err == nil {
						r.Body = io.NopCloser(bytes.NewBuffer(modBytes))
						r.ContentLength = int64(len(modBytes))
					}
				}
			}
		}
		// Ensure required fields are present
		if body == nil {
			log.Print("[MaximSDK] Request body is empty")
			body = make(map[string]interface{})
		}
		var model string
		var messages []schemas.CompletionRequest
		if payloadMessages, ok := body["messages"].([]interface{}); ok {
			messages = make([]schemas.CompletionRequest, 0, len(payloadMessages))
			for _, msg := range payloadMessages {
				if msgMap, ok := msg.(map[string]interface{}); ok {
					messages = append(messages, schemas.CompletionRequest{
						Role:    msgMap["role"].(string),
						Content: msgMap["content"],
					})
				}
			}
		}
		// Ensure model is a string
		if _, ok := body["model"].(string); ok {
			model = body["model"].(string)
		}
		// Extract model parameters into a separate map
		modelParams := make(map[string]interface{})
		for k, v := range body {
			if k != "model" && k != "messages" {
				modelParams[k] = v
			}
		}
		if model != "" {
			generation = trace.AddGeneration(&logging.GenerationConfig{
				Id:              uuid.New().String(),
				Name:            &contextValues.GenerationName,
				Provider:        provider,
				Model:           model,
				ModelParameters: modelParams,
				Messages:        messages,
				Tags:            &contextValues.GenerationTags,
			})
			defer generation.End()
			for k, v := range contextValues.GenerationMetrics {
				generation.AddMetric(k, v)
			}
			addAttachmentsFromOpenAIMessages(body, generation)
		}
	}
	resp, originalErr := next(r)
	if logger != nil {
		var result map[string]interface{}
		streamRequest := false
		if body != nil {
			if streamVal, ok := body["stream"]; ok {
				switch v := streamVal.(type) {
				case bool:
					streamRequest = v
				case *bool:
					streamRequest = v != nil && *v
				}
			}
		}
		// Clone and print the response
		if resp != nil && resp.Body != nil {
			respBytes, err := io.ReadAll(resp.Body)
			_ = resp.Body.Close()
			if err != nil {
				log.Print("[MaximSDK] Error reading response body:", err)
			}
			// Always restore body so downstream consumers can read (even if partial)
			resp.Body = io.NopCloser(bytes.NewBuffer(respBytes))
			if streamRequest && resp.StatusCode < 400 && len(respBytes) > 0 {
				result = parseOpenAIStreamResponse(respBytes)
			} else if err := json.Unmarshal(respBytes, &result); err != nil {
				if !streamRequest {
					log.Print("[MaximSDK] Error parsing OpenAI response:", err)
				}
			}
		}

		if generation != nil {
			apiErr := extractOpenAIAPIError(resp, result)
			if originalErr != nil {
				generation.SetError(&schemas.GenerationError{
					Message: originalErr.Error(),
				})
			} else if apiErr != nil {
				generation.SetError(apiErr)
				generation.SetResult(result)
			} else {
				if result != nil {
					openaiResult, err := logging.ParseResult(logging.ProviderOpenAI, "", result)
					if err != nil {
						log.Println("[MaximSDK] Error parsing OpenAI response:", err)
					} else if len(openaiResult.Choices) > 0 {
						trace.SetOutput(openaiResult.Choices[0].Message.Content)
					}
				}
				generation.SetResult(result)
			}
		}
	}
	return resp, originalErr
}

// parseOpenAIStreamResponse parses an SSE stream response and returns an aggregated result
// in the same shape as a non-streaming OpenAI chat completion.
func parseOpenAIStreamResponse(respBytes []byte) map[string]interface{} {
	type toolCallAcc struct {
		id        string
		typ       string
		name      string
		arguments strings.Builder
	}
	var content strings.Builder
	var id, model, finishReason string
	var usage map[string]interface{}
	toolCallsMap := make(map[int]*toolCallAcc)

	lines := strings.Split(string(respBytes), "\n")
	for _, line := range lines {
		data, ok := strings.CutPrefix(line, "data: ")
		if !ok {
			continue
		}
		if data == "" || data == "[DONE]" {
			continue
		}
		var chunk map[string]interface{}
		if err := json.Unmarshal([]byte(data), &chunk); err != nil {
			continue
		}
		if id == "" {
			if s, ok := chunk["id"].(string); ok {
				id = s
			}
		}
		if model == "" {
			if s, ok := chunk["model"].(string); ok {
				model = s
			}
		}
		// Usage is sent in the last chunk when stream_options.include_usage is true; take the latest
		if u, ok := chunk["usage"].(map[string]interface{}); ok && len(u) > 0 {
			usage = u
		}
		choices, _ := chunk["choices"].([]interface{})
		if len(choices) == 0 {
			continue
		}
		choice, _ := choices[0].(map[string]interface{})
		if fr, ok := choice["finish_reason"].(string); ok && fr != "" {
			finishReason = fr
		}
		delta, _ := choice["delta"].(map[string]interface{})
		if c, ok := delta["content"].(string); ok && c != "" {
			content.WriteString(c)
		}
		if tcs, ok := delta["tool_calls"].([]interface{}); ok {
			for _, tc := range tcs {
				tcMap, ok := tc.(map[string]interface{})
				if !ok {
					continue
				}
				idx := 0
				if idxVal, ok := tcMap["index"].(float64); ok {
					idx = int(idxVal)
				}
				if _, exists := toolCallsMap[idx]; !exists {
					toolCallsMap[idx] = &toolCallAcc{typ: "function"}
				}
				acc := toolCallsMap[idx]
				if tcID, ok := tcMap["id"].(string); ok && tcID != "" {
					acc.id = tcID
				}
				if typ, ok := tcMap["type"].(string); ok && typ != "" {
					acc.typ = typ
				}
				if fn, ok := tcMap["function"].(map[string]interface{}); ok {
					if name, ok := fn["name"].(string); ok && name != "" {
						acc.name = name
					}
					if args, ok := fn["arguments"].(string); ok {
						acc.arguments.WriteString(args)
					}
				}
			}
		}
	}
	if id == "" {
		id = "stream"
	}
	if finishReason == "" {
		finishReason = "stop"
	}
	message := map[string]interface{}{
		"role":    "assistant",
		"content": content.String(),
	}
	if len(toolCallsMap) > 0 {
		toolCalls := make([]map[string]interface{}, len(toolCallsMap))
		for idx, acc := range toolCallsMap {
			toolCalls[idx] = map[string]interface{}{
				"id":   acc.id,
				"type": acc.typ,
				"function": map[string]interface{}{
					"name":      acc.name,
					"arguments": acc.arguments.String(),
				},
			}
		}
		message["tool_calls"] = toolCalls
	}
	result := map[string]interface{}{
		"id":    id,
		"model": model,
		"choices": []map[string]interface{}{
			{
				"index":        0,
				"message":      message,
				"finish_reason": finishReason,
			},
		},
	}
	if usage != nil {
		result["usage"] = usage
	} else {
		result["usage"] = map[string]interface{}{"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}
	}
	return result
}

// extractOpenAIAPIError extracts API-level errors from the OpenAI response.
// OpenAI returns {"error": {"message": "...", "type": "...", "code": "..."}}.
func extractOpenAIAPIError(resp *http.Response, result map[string]interface{}) *schemas.GenerationError {
	if result == nil {
		if resp != nil && resp.StatusCode >= 400 {
			msg := resp.Status
			if msg == "" {
				msg = http.StatusText(resp.StatusCode)
			}
			return &schemas.GenerationError{Message: msg}
		}
		return nil
	}
	if errObj, ok := result["error"]; ok && errObj != nil {
		switch e := errObj.(type) {
		case map[string]interface{}:
			msg, _ := e["message"].(string)
			if msg == "" {
				msg = "unknown API error"
			}
			ge := &schemas.GenerationError{Message: msg}
			if code, ok := e["code"].(string); ok {
				ge.Code = &code
			}
			if errType, ok := e["type"].(string); ok {
				ge.Type = &errType
			}
			return ge
		}
	}
	if resp != nil && resp.StatusCode >= 400 {
		return &schemas.GenerationError{Message: resp.Status}
	}
	return nil
}

// addAttachmentsFromOpenAIMessages extracts image_url from OpenAI messages
// and adds them as attachments to the generation for display in Maxim.
func addAttachmentsFromOpenAIMessages(body map[string]interface{}, generation *logging.Generation) {
	if body == nil || generation == nil {
		return
	}
	messages, ok := body["messages"].([]interface{})
	if !ok {
		return
	}
	for _, m := range messages {
		msgMap, ok := m.(map[string]interface{})
		if !ok {
			continue
		}
		content, ok := msgMap["content"]
		if !ok {
			continue
		}
		contentArr, ok := content.([]interface{})
		if !ok {
			continue
		}
		for _, part := range contentArr {
			partMap, ok := part.(map[string]interface{})
			if !ok {
				continue
			}
			if partMap["type"] != "image_url" {
				continue
			}
			imgURL, ok := partMap["image_url"].(map[string]interface{})
			if !ok {
				continue
			}
			urlVal, ok := imgURL["url"].(string)
			if !ok || urlVal == "" {
				continue
			}
			if att := attachmentFromOpenAIImageURL(urlVal); att != nil {
				generation.AddAttachment(att)
			}
		}
	}
}

// attachmentFromOpenAIImageURL creates UrlAttachment or FileDataAttachment from OpenAI image_url.
func attachmentFromOpenAIImageURL(urlStr string) interface{} {
	if urlStr == "" {
		return nil
	}
	// data:image/jpeg;base64,... -> FileDataAttachment
	if strings.HasPrefix(urlStr, "data:") {
		return attachmentFromOpenAIDataURL(urlStr)
	}
	// http/https URLs -> UrlAttachment
	if strings.HasPrefix(urlStr, "http://") || strings.HasPrefix(urlStr, "https://") {
		ext := ".jpg"
		mimeType := "image/jpeg"
		if strings.Contains(urlStr, ".png") {
			ext = ".png"
			mimeType = "image/png"
		} else if strings.Contains(urlStr, ".gif") {
			ext = ".gif"
			mimeType = "image/gif"
		} else if strings.Contains(urlStr, ".webp") {
			ext = ".webp"
			mimeType = "image/webp"
		}
		return &logging.UrlAttachment{
			BaseAttachmentProps: logging.BaseAttachmentProps{
				ID:       uuid.New().String(),
				Name:     "input_image" + ext,
				MimeType: mimeType,
				Tags:     map[string]string{"source": "openai_vision_input"},
			},
			Type: logging.AttachmentTypeURL,
			URL:  urlStr,
		}
	}
	return nil
}

func attachmentFromOpenAIDataURL(dataURL string) *logging.FileDataAttachment {
	// Format: data:image/jpeg;base64,<base64data>
	parts := strings.SplitN(dataURL, ",", 2)
	if len(parts) != 2 {
		return nil
	}
	header := parts[0]
	b64Data := parts[1]
	data, err := base64.StdEncoding.DecodeString(b64Data)
	if err != nil {
		log.Printf("[MaximSDK] Failed to decode OpenAI data URL base64: %v", err)
		return nil
	}
	mimeType := "application/octet-stream"
	if strings.HasPrefix(header, "data:") {
		mimePart := strings.TrimPrefix(header, "data:")
		if semicolon := strings.Index(mimePart, ";"); semicolon >= 0 {
			mimeType = mimePart[:semicolon]
		}
	}
	ext := ".bin"
	if strings.HasPrefix(mimeType, "image/") {
		ext = "." + strings.TrimPrefix(mimeType, "image/")
	}
	return &logging.FileDataAttachment{
		BaseAttachmentProps: logging.BaseAttachmentProps{
			ID:       uuid.New().String(),
			Name:     "input_image" + ext,
			MimeType: mimeType,
			Tags:     map[string]string{"source": "openai_vision_input"},
		},
		Type: logging.AttachmentTypeFileData,
		Data: data,
	}
}
