package middlewares

import (
	"bytes"
	"encoding/json"
	"io"
	"log"
	"net/http"

	"github.com/google/uuid"
	"github.com/maximhq/maxim-go/logging"
)

func MaximOpenAIMiddleware(r *http.Request, next func(*http.Request) (*http.Response, error)) (*http.Response, error) {
	var resp *http.Response
	var logger *logging.Logger
	// Getting logger
	if r.Context().Value("maxim.logger") != nil {
		logger = r.Context().Value("maxim.logger").(*logging.Logger)
	} else if autoGeneratedLogger != nil {
		logger = autoGeneratedLogger
	} else {
		log.Println("[MaximSDK] Logger is not availble in the context. Please attach maxim.logger to logging.Logger to trace using middlewares")
	}
	var trace *logging.Trace
	var generation *logging.Generation
	if logger != nil {
		provider := logging.ProviderOpenAI
		if r.Context().Value("maxim.provider") != nil {
			provider = r.Context().Value("maxim.provider").(string)
		}
		contextValues := parseContextValues(r.Context())
		// Clone the body of the request if it exists
		trace = logger.Trace(&logging.TraceConfig{
			Id:   contextValues.TraceId,
			Name: &contextValues.TraceName,
			Tags: &contextValues.TraceTags,
		})
		var body map[string]interface{}
		if r.Body != nil {
			bodyBytes, err := io.ReadAll(r.Body)
			if err != nil {
				return nil, err
			}
			// Create two readers from the bytes
			r.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Note: We don't need to create a second reader here since we're just passing through
			// If needed, create another reader: bodyClone := io.NopCloser(bytes.NewBuffer(bodyBytes))
			// Print the request body for debugging
			if err := json.Unmarshal(bodyBytes, &body); err != nil {
				// Log or handle the error as needed
				// For now, just continue with the execution
				log.Print("[MaximSDK] Couldn't parse OpenAI request")
			}
		}
		// Ensure required fields are present
		if body == nil {
			log.Print("[MaximSDK] Request body is empty")
			body = make(map[string]interface{})
		}
		var model string
		var messages []logging.CompletionRequest
		if _, ok := body["messages"].([]interface{}); ok {
			payloadMessages := body["messages"].([]interface{})
			messages = make([]logging.CompletionRequest, len(payloadMessages))
			for i, msg := range payloadMessages {
				messages[i] = logging.CompletionRequest{
					Role:    msg.(map[string]interface{})["role"].(string),
					Content: msg.(map[string]interface{})["content"],
				}
			}
		}
		// Ensure model is a string
		if _, ok := body["model"].(string); ok {
			model = body["model"].(string)
		}
		// Extract model parameters into a separate map
		modelParams := make(map[string]interface{})
		for k, v := range body {
			if k != "model" && k != "messages" {
				modelParams[k] = v
			}
		}
		if model != "" {
			generation = trace.AddGeneration(&logging.GenerationConfig{
				Id:              uuid.New().String(),
				Name:            &contextValues.GenerationName,
				Provider:        provider,
				Model:           model,
				ModelParameters: modelParams,
				Messages:        messages,
				Tags:            &contextValues.GenerationTags,
			})
			defer generation.End()
		}
	}
	resp, originalErr := next(r)
	if logger != nil {
		var result map[string]interface{}
		// Clone and print the response
		if resp != nil && resp.Body != nil {
			respBytes, err := io.ReadAll(resp.Body)
			if err != nil {
				log.Print("[MaximSDK] Error reading response body:", err)
			} else {
				// Create a new reader from the bytes
				resp.Body = io.NopCloser(bytes.NewBuffer(respBytes))
			}
			// Parse response bytes into result
			if err := json.Unmarshal(respBytes, &result); err != nil {
				log.Print("[MaximSDK] Error parsing OpenAI response:", err)
			}
		}

		if generation != nil {
			if originalErr != nil {
				generation.SetError(&logging.GenerationError{
					Message: originalErr.Error(),
				})
			} else {
				generation.SetResult(result)
			}
		}
	}
	return resp, originalErr
}
