package middlewares

import (
	"context"
	"log"
	"net/http"

	"github.com/maximhq/maxim-go/logging"
)

// MaximVertexTransport is an http.RoundTripper for the Vertex AI Gemini API
// (aiplatform.googleapis.com). Use with http.Client{Transport: middlewares.NewMaximVertexTransport(logger)}.
//
// Vertex AI uses the same wire format as the Gemini API, so this transport delegates
// to MaximGeminiMiddleware with the provider set to logging.ProviderVertex.
type MaximVertexTransport struct {
	Logger *logging.Logger
}

// NewMaximVertexTransport creates a transport for tracing Vertex AI API calls to Maxim.
func NewMaximVertexTransport(logger *logging.Logger) *MaximVertexTransport {
	return &MaximVertexTransport{Logger: logger}
}

// RoundTrip implements http.RoundTripper for use with http.Client.
func (t *MaximVertexTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	return t.Do(req)
}

// Do executes the request with Maxim tracing. It sets the provider to logging.ProviderVertex
// and delegates to MaximGeminiMiddleware, which handles the Gemini-compatible Vertex AI wire format.
func (t *MaximVertexTransport) Do(req *http.Request) (*http.Response, error) {
	if t.Logger == nil && autoGeneratedLogger == nil {
		log.Println("[MaximSDK] Initialize VertexTransport with logging.Logger object. Currently Maxim tracing is disabled as logger is not available.")
	}
	logger := t.Logger
	if logger == nil {
		logger = autoGeneratedLogger
	}
	if logger != nil {
		ctx := context.WithValue(req.Context(), ContextKeyLogger, logger)
		ctx = context.WithValue(ctx, ContextKeyProvider, logging.ProviderVertex)
		req = req.WithContext(ctx)
	}
	return MaximGeminiMiddleware(req, func(req *http.Request) (*http.Response, error) {
		return http.DefaultTransport.RoundTrip(req)
	})
}
